// <auto-generated />
using API.Login.Infra.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Login.Infra.Migrations
{
    [DbContext(typeof(SqlLiteContext))]
    [Migration("20240610225618_updatingUserEntity")]
    partial class updatingUserEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("API.Login.Domain.Entities.User.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("UserId");

                    b.Property<int>("Ativo")
                        .HasColumnType("int")
                        .HasColumnName("Ativo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasColumnName("Email");

                    b.Property<string>("EmailHash")
                        .HasColumnType("varchar")
                        .HasColumnName("EmailHash");

                    b.Property<int>("Logado")
                        .HasColumnType("int")
                        .HasColumnName("Logado");

                    b.Property<byte[]>("PassWordHash")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("PassWordHash");

                    b.Property<byte[]>("PassWordSalt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("BLOB")
                        .HasColumnName("PassWordSalt");

                    b.Property<string>("SessionJwt")
                        .HasColumnType("varchar")
                        .HasColumnName("SessionJwt");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasColumnName("UserName");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
